CC = gcc
C_STD = -std=c99
TARGET = bin/main
INCLUDE = include/
LIB = lib/
LIBS = -lmingw32 -lSDL2main -lSDL2 -lglfw3 -lopengl32 -lgdi32
MAIN = glad.c main.c 
OBJ = obj/
OBJS = obj/*.o


run : compile
	./bin/main

compile : compile_shader_reader
	$(CC) $(C_STD) -I $(INCLUDE) -L $(LIB) -o $(TARGET) $(MAIN) $(OBJS) $(LIBS)

compile_shader_reader :
	$(CC) -c $(C_STD) -I $(INCLUDE) -L $(LIB) -o $(OBJ)shader_reader.o src/shader_reader.c
